{% set name = "event-model" %}
{% set version = "1.19.0" %}
{% set sha256 = "4f7338e45adef62bf2cae756c472b41c96fecd239ece96b2c64a45741f291dcf" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - jsonschema
    - numpy
    - setuptools  # provides 'pkg_resources'

test:
  requires:
    - pytest
  imports:
    - event_model
  commands:
    - pytest --pyargs event_model.tests

about:
  home: https://github.com/bluesky/event-model
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Data model for event-based data collection and analysis

extra:
  recipe-maintainers:
    - danielballan
    - mrakitin
    - stuartcampbell
    - tacaswell
    - gwbischof
