{% set version = "1.10.0" %}

package:
  name: event-model
  version: {{ version }}

source:
  url: https://github.com/NSLS-II/event-model/archive/v{{ version }}.tar.gz
  fn: event-model-v{{version}}.tar.gz
  sha256: ee2b6957703c623fb2b49bb4dbd6c2146d63d31a57d5fb6e2965d2cf13c6510a

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  noarch: python

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - jsonschema
    - numpy

test:
  imports:
    - event_model

about:
  home: https://github.com/NSLS-II/event-model
  license: BSD 3-Clause
  summary: data model for event-based data collection and analysis

extra:
  recipe-maintainers:
    - CJ-Wright
    - mrakitin
    - tacaswell
    - danielballan
