{% set version = "1.5.0" %}

package:
    name: event-model
    version: {{ version }}

source:
    url: https://github.com/NSLS-II/event-model/archive/v{{ version }}.tar.gz
    fn: event-model-v{{version}}.tar.gz
    sha256: d1a1fbb4076a8387bfd96f35f3acc97f7b1ef8cd31a7f4359ebc9a2536c715a7

build:
    number: 1000
    script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
    build:
        - python
        - setuptools

    run:
        - python
        - enum34  # [py2k]
        - setuptools

test:
    imports:
        - event_model

about:
    home: https://github.com/NSLS-II/event-model
    license: BSD 3-Clause
    summary: data model for event-based data collection and analysis

extra:
    recipe-maintainers:
        - ericdill
        - licode
        - tacaswell
        - CJ-Wright
