travis:
  secure:
    BINSTAR_TOKEN: s2BYtWVS82faYnBN2KQU+NTN/UUE3Y00T+mmn9XU1iUL0AVTum1uBEjei6dv+BiprIlzVe1ycisrMwFuZxOZGGgBOnaQHQJ6tcTE3ZRMqSeVHomtOiiluirZGFrXv4VhuI/UEDHWxIwVwIOMxIcdg/JZmv2u56mrIsnht0XC5akowwJgjLh2OBdS1ljMxXYJKucNH0ZAGaYaGsWq+iIa6vZYlons3Wh7CGTGjbBPIaBY/E/MoPnAiHIAQLTKoDtLqzz+zXgs6chlzz9dCIFmZ90zT4KLq4BHmgCDDLxImZNieS1KYL9wXHPHY+s2porbozF8Ckb9Stjss/VOZ6NJyfEEWUOl5E3QFhy80VaDAKfA7wNj0LeMPMjamffZEQdvspR1rA1veetUfFidC4G/xPkom61u8qT59RkRm/qg0hD9hrYpTnn7t983MCv0r+mVY1jVzjp0BzgIHvUxZhYle9LBRmIfR3WIO2psYmnCO4qgwdVSvR9vru5W+4UUkqKuWCnzyQ0yiOZ35+pyu6WRws2+y02mcwJD9wDk3cdHyCFRbMcFuBedq+I/Uy8kVhNhkX3L46ftAn+i/Vm/rudbyjx1q1db/OsMk1f2V+2fbMJoCMHqo6ab6zhEerVMb1CCCsXHic+Y1GMxAQNT4QCTZXdtOwAmEqnPgX+E9SDxzzw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
