travis:
  secure:
    BINSTAR_TOKEN: TGKmdDfrgoc5JPipyEfYourqRNK2sFcKZPafVsraArWhWxif38eKfp+Q43eJptSRFpNIByDb5j/mAyUsBELblg7j32DtEI9Ieg8ahqmKD3QGgPETpX5XWyxWfueEV0Zu7S//D4ARWcAYXuI/5fsbdv9JszwYoxGr9tmtVP7ST78DcMOD8jq72xIRKFjbI3Z7t/pv+RSI0mm0j+UOAMTY/ANg/yBaoyp7hQdFlSdhIRkkVdPMt5Dl9PhGtMkjWn0kgRJpF92mALGOpEnGXYoSwrv/lHg/SfnFHnMFTelXFqSiGVRwmlNdSlT4zz2RFqrSrVHgsdUGF9s6nT7VcuPVoOtC9D8HuhBHwifIzHMxQN5r7jDSN+1wmyhNlLRgdR5YQE84NES6w0NgqHQTXwfhhdBscnrClMPeMq74eV226vQNBS5vf5eSsG1mDyDFYxZxCxXyxeChPRHfIhxVmJWMq/IeeH6wf/IH8Alfe9WLLQAWIeRxOD054bHlGqeC+sNeJHWTj2SlQVLdTitNEtT4WPt+fEfZRNPa1QRB6IIfRFFsMPIm3+jebtvKYSb555WIZEZKbCqh1OxT9SiVHsUlY3vA/o3HN+FAKF7GSN4lhP2g/KwZvB5ghG9YomrNFzhgkg26NVWzwrJ8f2qT3OzTxhiwYBEhrCfewJiV0ISWsIU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
